#+TITLE: README
#+AUTHOR: Eduardo Robles
#+EMAIL: eduardorobles@proton.me
* Literate SecOps
** Preamble
I was demonstrating how I use Emacs and Org-mode to organize my work. While doing so I found my workflow is unique and reproducible. I had spoken about this idea and it my workflow mimics that already studied. Literate DevOps is a concept developed by Emacs user Howard Abrams. I propose something new for those in the Cybersecurity field: Literate SecOps.
** About
Literate SecOps is the act of defining your documentation, communications, and code.
** Prerequisites
- Emacs
- Org-mode
** Installing
Download the templates and start using with Emacs.
** Usage
Most templates leverage Emacs or Org-mode features/packages such as:
- Org babel
- Yassnippet
- Verb
- Eshell
** Authors
[[https://eduardorobles.com][Eduardo Robles]] - Idea
** Acknowledgements
[[https://howardism.org/Technical/Emacs/literate-devops.html][Literate DevOps]] by Howard Abrams
** References
- [[https://www.eduardorobles.com/posts/cyber-work-templates-by-me/][Cyber Work Templates]] by Eduardo Robles
- [[https://www.eduardorobles.com/posts/conducting-cybersecurity-investigations-in-emacs/][Conducting Cybersecurity Investigations in Emacs]] by Eduardo Robles
** License
MIT
** Contributions
